version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "winston-sam-project"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-drmcob6sr0qu"
s3_prefix = "winston-sam-project"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=253896803446.dkr.ecr.us-west-2.amazonaws.com/hello-winston", "GetRoundsFunction=253896803446.dkr.ecr.us-west-2.amazonaws.com/winston-rounds"]
